import { Default_CoreStyles as dflt } from "./Default_CoreStyles";

const maxWidth = 960;
export const Large_CoreStyles = {
  container: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_sm: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_md: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_lg: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  row: dflt.row,
  col_lg: dflt.col,
  col_lg_auto: dflt.col_auto,
  col_lg_1: dflt.col_1,
  col_lg_2: dflt.col_2,
  col_lg_3: dflt.col_3,
  col_lg_4: dflt.col_4,
  col_lg_5: dflt.col_5,
  col_lg_6: dflt.col_6,
  col_lg_7: dflt.col_7,
  col_lg_8: dflt.col_8,
  col_lg_9: dflt.col_9,
  col_lg_10: dflt.col_10,
  col_lg_11: dflt.col_11,
  col_lg_12: dflt.col_12,

  offset_lg_0: {
    marginLeft: 0,
  },
  offset_lg_1: dflt.offset_1,
  offset_lg_2: dflt.offset_2,
  offset_lg_3: dflt.offset_3,
  offset_lg_4: dflt.offset_4,
  offset_lg_5: dflt.offset_5,
  offset_lg_6: dflt.offset_6,
  offset_lg_7: dflt.offset_7,
  offset_lg_8: dflt.offset_8,
  offset_lg_9: dflt.offset_9,
  offset_lg_10: dflt.offset_10,
  offset_lg_11: dflt.offset_11,

  mt_lg_0: dflt.mt_0,
  mt_lg_1: dflt.mt_1,
  mt_lg_2: dflt.mt_2,
  mt_lg_3: dflt.mt_3,
  mt_lg_4: dflt.mt_4,
  mt_lg_5: dflt.mt_5,
  mt_lg_auto: dflt.mt_auto,
  mb_lg_0: dflt.mb_0,
  mb_lg_1: dflt.mb_1,
  mb_lg_2: dflt.mb_2,
  mb_lg_3: dflt.mb_3,
  mb_lg_4: dflt.mb_4,
  mb_lg_5: dflt.mb_5,
  mb_lg_auto: dflt.mb_auto,
  ms_lg_0: dflt.ms_0,
  ms_lg_1: dflt.ms_1,
  ms_lg_2: dflt.ms_2,
  ms_lg_3: dflt.ms_3,
  ms_lg_4: dflt.ms_4,
  ms_lg_5: dflt.ms_5,
  ms_lg_auto: dflt.ms_auto,
  me_lg_0: dflt.me_0,
  me_lg_1: dflt.me_1,
  me_lg_2: dflt.me_2,
  me_lg_3: dflt.me_3,
  me_lg_4: dflt.me_4,
  me_lg_5: dflt.me_5,
  me_lg_auto: dflt.me_auto,
  mx_lg_0: dflt.mx_0,
  mx_lg_1: dflt.mx_1,
  mx_lg_2: dflt.mx_2,
  mx_lg_3: dflt.mx_3,
  mx_lg_4: dflt.mx_4,
  mx_lg_5: dflt.mx_5,
  mx_lg_auto: dflt.mx_auto,
  my_lg_0: dflt.my_0,
  my_lg_1: dflt.my_1,
  my_lg_2: dflt.my_2,
  my_lg_3: dflt.my_3,
  my_lg_4: dflt.my_4,
  my_lg_5: dflt.my_5,
  my_lg_auto: dflt.my_auto,
  m_lg_0: dflt.m_0,
  m_lg_1: dflt.m_1,
  m_lg_2: dflt.m_2,
  m_lg_3: dflt.m_3,
  m_lg_4: dflt.m_4,
  m_lg_5: dflt.m_5,
  m_lg_auto: dflt.m_auto,

  pt_lg_0: dflt.pt_0,
  pt_lg_1: dflt.pt_1,
  pt_lg_2: dflt.pt_2,
  pt_lg_3: dflt.pt_3,
  pt_lg_4: dflt.pt_4,
  pt_lg_5: dflt.pt_5,
  pt_lg_auto: dflt.pt_auto,
  pb_lg_0: dflt.pb_0,
  pb_lg_1: dflt.pb_1,
  pb_lg_2: dflt.pb_2,
  pb_lg_3: dflt.pb_3,
  pb_lg_4: dflt.pb_4,
  pb_lg_5: dflt.pb_5,
  pb_lg_auto: dflt.pb_auto,
  ps_lg_0: dflt.ps_0,
  ps_lg_1: dflt.ps_1,
  ps_lg_2: dflt.ps_2,
  ps_lg_3: dflt.ps_3,
  ps_lg_4: dflt.ps_4,
  ps_lg_5: dflt.ps_5,
  ps_lg_auto: dflt.ps_auto,
  pe_lg_0: dflt.pe_0,
  pe_lg_1: dflt.pe_1,
  pe_lg_2: dflt.pe_2,
  pe_lg_3: dflt.pe_3,
  pe_lg_4: dflt.pe_4,
  pe_lg_5: dflt.pe_5,
  pe_lg_auto: dflt.pe_auto,
  px_lg_0: dflt.px_0,
  px_lg_1: dflt.px_1,
  px_lg_2: dflt.px_2,
  px_lg_3: dflt.px_3,
  px_lg_4: dflt.px_4,
  px_lg_5: dflt.px_5,
  px_lg_auto: dflt.px_auto,
  py_lg_0: dflt.py_0,
  py_lg_1: dflt.py_1,
  py_lg_2: dflt.py_2,
  py_lg_3: dflt.py_3,
  py_lg_4: dflt.py_4,
  py_lg_5: dflt.py_5,
  py_lg_auto: dflt.py_auto,
  p_lg_0: dflt.p_0,
  p_lg_1: dflt.p_1,
  p_lg_2: dflt.p_2,
  p_lg_3: dflt.p_3,
  p_lg_4: dflt.p_4,
  p_lg_5: dflt.p_5,
  p_lg_auto: dflt.p_auto,

  d_lg_none: { display: "none" },
  d_lg_block: { display: "flex" },
};
