import { Default_CoreStyles as dflt } from "./Default_CoreStyles";

const maxWidth = 540;
export const Small_CoreStyles = {
  container: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_sm: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  row: dflt.row,
  col_sm: dflt.col,
  col_sm_auto: dflt.col_auto,
  col_sm_1: dflt.col_1,
  col_sm_2: dflt.col_2,
  col_sm_3: dflt.col_3,
  col_sm_4: dflt.col_4,
  col_sm_5: dflt.col_5,
  col_sm_6: dflt.col_6,
  col_sm_7: dflt.col_7,
  col_sm_8: dflt.col_8,
  col_sm_9: dflt.col_9,
  col_sm_10: dflt.col_10,
  col_sm_11: dflt.col_11,
  col_sm_12: dflt.col_12,
  offset_sm_0: {
    marginLeft: 0,
  },
  offset_sm_1: dflt.offset_1,
  offset_sm_2: dflt.offset_2,
  offset_sm_3: dflt.offset_3,
  offset_sm_4: dflt.offset_4,
  offset_sm_5: dflt.offset_5,
  offset_sm_6: dflt.offset_6,
  offset_sm_7: dflt.offset_7,
  offset_sm_8: dflt.offset_8,
  offset_sm_9: dflt.offset_9,
  offset_sm_10: dflt.offset_10,
  offset_sm_11: dflt.offset_11,

  mt_sm_0: dflt.mt_0,
  mt_sm_1: dflt.mt_1,
  mt_sm_2: dflt.mt_2,
  mt_sm_3: dflt.mt_3,
  mt_sm_4: dflt.mt_4,
  mt_sm_5: dflt.mt_5,
  mt_sm_auto: dflt.mt_auto,
  mb_sm_0: dflt.mb_0,
  mb_sm_1: dflt.mb_1,
  mb_sm_2: dflt.mb_2,
  mb_sm_3: dflt.mb_3,
  mb_sm_4: dflt.mb_4,
  mb_sm_5: dflt.mb_5,
  mb_sm_auto: dflt.mb_auto,
  ms_sm_0: dflt.ms_0,
  ms_sm_1: dflt.ms_1,
  ms_sm_2: dflt.ms_2,
  ms_sm_3: dflt.ms_3,
  ms_sm_4: dflt.ms_4,
  ms_sm_5: dflt.ms_5,
  ms_sm_auto: dflt.ms_auto,
  me_sm_0: dflt.me_0,
  me_sm_1: dflt.me_1,
  me_sm_2: dflt.me_2,
  me_sm_3: dflt.me_3,
  me_sm_4: dflt.me_4,
  me_sm_5: dflt.me_5,
  me_sm_auto: dflt.me_auto,
  mx_sm_0: dflt.mx_0,
  mx_sm_1: dflt.mx_1,
  mx_sm_2: dflt.mx_2,
  mx_sm_3: dflt.mx_3,
  mx_sm_4: dflt.mx_4,
  mx_sm_5: dflt.mx_5,
  mx_sm_auto: dflt.mx_auto,
  my_sm_0: dflt.my_0,
  my_sm_1: dflt.my_1,
  my_sm_2: dflt.my_2,
  my_sm_3: dflt.my_3,
  my_sm_4: dflt.my_4,
  my_sm_5: dflt.my_5,
  my_sm_auto: dflt.my_auto,
  m_sm_0: dflt.m_0,
  m_sm_1: dflt.m_1,
  m_sm_2: dflt.m_2,
  m_sm_3: dflt.m_3,
  m_sm_4: dflt.m_4,
  m_sm_5: dflt.m_5,
  m_sm_auto: dflt.m_auto,

  pt_sm_0: dflt.pt_0,
  pt_sm_1: dflt.pt_1,
  pt_sm_2: dflt.pt_2,
  pt_sm_3: dflt.pt_3,
  pt_sm_4: dflt.pt_4,
  pt_sm_5: dflt.pt_5,
  pt_sm_auto: dflt.pt_auto,
  pb_sm_0: dflt.pb_0,
  pb_sm_1: dflt.pb_1,
  pb_sm_2: dflt.pb_2,
  pb_sm_3: dflt.pb_3,
  pb_sm_4: dflt.pb_4,
  pb_sm_5: dflt.pb_5,
  pb_sm_auto: dflt.pb_auto,
  ps_sm_0: dflt.ps_0,
  ps_sm_1: dflt.ps_1,
  ps_sm_2: dflt.ps_2,
  ps_sm_3: dflt.ps_3,
  ps_sm_4: dflt.ps_4,
  ps_sm_5: dflt.ps_5,
  ps_sm_auto: dflt.ps_auto,
  pe_sm_0: dflt.pe_0,
  pe_sm_1: dflt.pe_1,
  pe_sm_2: dflt.pe_2,
  pe_sm_3: dflt.pe_3,
  pe_sm_4: dflt.pe_4,
  pe_sm_5: dflt.pe_5,
  pe_sm_auto: dflt.pe_auto,
  px_sm_0: dflt.px_0,
  px_sm_1: dflt.px_1,
  px_sm_2: dflt.px_2,
  px_sm_3: dflt.px_3,
  px_sm_4: dflt.px_4,
  px_sm_5: dflt.px_5,
  px_sm_auto: dflt.px_auto,
  py_sm_0: dflt.py_0,
  py_sm_1: dflt.py_1,
  py_sm_2: dflt.py_2,
  py_sm_3: dflt.py_3,
  py_sm_4: dflt.py_4,
  py_sm_5: dflt.py_5,
  py_sm_auto: dflt.py_auto,
  p_sm_0: dflt.p_0,
  p_sm_1: dflt.p_1,
  p_sm_2: dflt.p_2,
  p_sm_3: dflt.p_3,
  p_sm_4: dflt.p_4,
  p_sm_5: dflt.p_5,
  p_sm_auto: dflt.p_auto,

  d_sm_none: { display: "none" },
  d_sm_block: { display: "flex" },
};
