import { remToPx } from "./BsStylesConstants";
import { Default_CoreStyles as dflt } from "./Default_CoreStyles";

const maxWidth = 1140;
export const XLarge_CoreStyles = {
  container: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_sm: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_md: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_lg: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_xl: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  row: dflt.row,
  col_xl: dflt.col,
  col_xl_auto: dflt.col_auto,
  col_xl_1: dflt.col_1,
  col_xl_2: dflt.col_2,
  col_xl_3: dflt.col_3,
  col_xl_4: dflt.col_4,
  col_xl_5: dflt.col_5,
  col_xl_6: dflt.col_6,
  col_xl_7: dflt.col_7,
  col_xl_8: dflt.col_8,
  col_xl_9: dflt.col_9,
  col_xl_10: dflt.col_10,
  col_xl_11: dflt.col_11,
  col_xl_12: dflt.col_12,

  offset_xl_0: {
    marginLeft: 0,
  },
  offset_xl_1: dflt.offset_1,
  offset_xl_2: dflt.offset_2,
  offset_xl_3: dflt.offset_3,
  offset_xl_4: dflt.offset_4,
  offset_xl_5: dflt.offset_5,
  offset_xl_6: dflt.offset_6,
  offset_xl_7: dflt.offset_7,
  offset_xl_8: dflt.offset_8,
  offset_xl_9: dflt.offset_9,
  offset_xl_10: dflt.offset_10,
  offset_xl_11: dflt.offset_11,

  mt_xl_0: dflt.mt_0,
  mt_xl_1: dflt.mt_1,
  mt_xl_2: dflt.mt_2,
  mt_xl_3: dflt.mt_3,
  mt_xl_4: dflt.mt_4,
  mt_xl_5: dflt.mt_5,
  mt_xl_auto: dflt.mt_auto,
  mb_xl_0: dflt.mb_0,
  mb_xl_1: dflt.mb_1,
  mb_xl_2: dflt.mb_2,
  mb_xl_3: dflt.mb_3,
  mb_xl_4: dflt.mb_4,
  mb_xl_5: dflt.mb_5,
  mb_xl_auto: dflt.mb_auto,
  ms_xl_0: dflt.ms_0,
  ms_xl_1: dflt.ms_1,
  ms_xl_2: dflt.ms_2,
  ms_xl_3: dflt.ms_3,
  ms_xl_4: dflt.ms_4,
  ms_xl_5: dflt.ms_5,
  ms_xl_auto: dflt.ms_auto,
  me_xl_0: dflt.me_0,
  me_xl_1: dflt.me_1,
  me_xl_2: dflt.me_2,
  me_xl_3: dflt.me_3,
  me_xl_4: dflt.me_4,
  me_xl_5: dflt.me_5,
  me_xl_auto: dflt.me_auto,
  mx_xl_0: dflt.mx_0,
  mx_xl_1: dflt.mx_1,
  mx_xl_2: dflt.mx_2,
  mx_xl_3: dflt.mx_3,
  mx_xl_4: dflt.mx_4,
  mx_xl_5: dflt.mx_5,
  mx_xl_auto: dflt.mx_auto,
  my_xl_0: dflt.my_0,
  my_xl_1: dflt.my_1,
  my_xl_2: dflt.my_2,
  my_xl_3: dflt.my_3,
  my_xl_4: dflt.my_4,
  my_xl_5: dflt.my_5,
  my_xl_auto: dflt.my_auto,
  m_xl_0: dflt.m_0,
  m_xl_1: dflt.m_1,
  m_xl_2: dflt.m_2,
  m_xl_3: dflt.m_3,
  m_xl_4: dflt.m_4,
  m_xl_5: dflt.m_5,
  m_xl_auto: dflt.m_auto,

  pt_xl_0: dflt.pt_0,
  pt_xl_1: dflt.pt_1,
  pt_xl_2: dflt.pt_2,
  pt_xl_3: dflt.pt_3,
  pt_xl_4: dflt.pt_4,
  pt_xl_5: dflt.pt_5,
  pt_xl_auto: dflt.pt_auto,
  pb_xl_0: dflt.pb_0,
  pb_xl_1: dflt.pb_1,
  pb_xl_2: dflt.pb_2,
  pb_xl_3: dflt.pb_3,
  pb_xl_4: dflt.pb_4,
  pb_xl_5: dflt.pb_5,
  pb_xl_auto: dflt.pb_auto,
  ps_xl_0: dflt.ps_0,
  ps_xl_1: dflt.ps_1,
  ps_xl_2: dflt.ps_2,
  ps_xl_3: dflt.ps_3,
  ps_xl_4: dflt.ps_4,
  ps_xl_5: dflt.ps_5,
  ps_xl_auto: dflt.ps_auto,
  pe_xl_0: dflt.pe_0,
  pe_xl_1: dflt.pe_1,
  pe_xl_2: dflt.pe_2,
  pe_xl_3: dflt.pe_3,
  pe_xl_4: dflt.pe_4,
  pe_xl_5: dflt.pe_5,
  pe_xl_auto: dflt.pe_auto,
  px_xl_0: dflt.px_0,
  px_xl_1: dflt.px_1,
  px_xl_2: dflt.px_2,
  px_xl_3: dflt.px_3,
  px_xl_4: dflt.px_4,
  px_xl_5: dflt.px_5,
  px_xl_auto: dflt.px_auto,
  py_xl_0: dflt.py_0,
  py_xl_1: dflt.py_1,
  py_xl_2: dflt.py_2,
  py_xl_3: dflt.py_3,
  py_xl_4: dflt.py_4,
  py_xl_5: dflt.py_5,
  py_xl_auto: dflt.py_auto,
  p_xl_0: dflt.p_0,
  p_xl_1: dflt.p_1,
  p_xl_2: dflt.p_2,
  p_xl_3: dflt.p_3,
  p_xl_4: dflt.p_4,
  p_xl_5: dflt.p_5,
  p_xl_auto: dflt.p_auto,

  /**
   * Heading(s)
   */

  h1: {
    ...dflt.h1,
    fontSize: remToPx(2.5),
  },
  h2: {
    ...dflt.h2,
    fontSize: remToPx(2),
  },
  h3: {
    ...dflt.h3,
    fontSize: remToPx(1.75),
  },
  h4: {
    ...dflt.h4,
    fontSize: remToPx(1.5),
  },

  d_xl_none: { display: "none" },
  d_xl_block: { display: "flex" },
};
