import { Default_CoreStyles as dflt } from "./Default_CoreStyles";

const maxWidth = 1320;
export const XXLarge_CoreStyles = {
  container: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_sm: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_md: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_lg: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_xl: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  container_xxl: {
    ...dflt.container,
    maxWidth: maxWidth,
  },
  row: dflt.row,
  col_xxl: dflt.col,
  col_xxl_auto: dflt.col_auto,
  col_xxl_1: dflt.col_1,
  col_xxl_2: dflt.col_2,
  col_xxl_3: dflt.col_3,
  col_xxl_4: dflt.col_4,
  col_xxl_5: dflt.col_5,
  col_xxl_6: dflt.col_6,
  col_xxl_7: dflt.col_7,
  col_xxl_8: dflt.col_8,
  col_xxl_9: dflt.col_9,
  col_xxl_10: dflt.col_10,
  col_xxl_11: dflt.col_11,
  col_xxl_12: dflt.col_12,

  offset_xxl_0: {
    marginLeft: 0,
  },
  offset_xxl_1: dflt.offset_1,
  offset_xxl_2: dflt.offset_2,
  offset_xxl_3: dflt.offset_3,
  offset_xxl_4: dflt.offset_4,
  offset_xxl_5: dflt.offset_5,
  offset_xxl_6: dflt.offset_6,
  offset_xxl_7: dflt.offset_7,
  offset_xxl_8: dflt.offset_8,
  offset_xxl_9: dflt.offset_9,
  offset_xxl_10: dflt.offset_10,
  offset_xxl_11: dflt.offset_11,

  mt_xxl_0: dflt.mt_0,
  mt_xxl_1: dflt.mt_1,
  mt_xxl_2: dflt.mt_2,
  mt_xxl_3: dflt.mt_3,
  mt_xxl_4: dflt.mt_4,
  mt_xxl_5: dflt.mt_5,
  mt_xxl_auto: dflt.mt_auto,
  mb_xxl_0: dflt.mb_0,
  mb_xxl_1: dflt.mb_1,
  mb_xxl_2: dflt.mb_2,
  mb_xxl_3: dflt.mb_3,
  mb_xxl_4: dflt.mb_4,
  mb_xxl_5: dflt.mb_5,
  mb_xxl_auto: dflt.mb_auto,
  ms_xxl_0: dflt.ms_0,
  ms_xxl_1: dflt.ms_1,
  ms_xxl_2: dflt.ms_2,
  ms_xxl_3: dflt.ms_3,
  ms_xxl_4: dflt.ms_4,
  ms_xxl_5: dflt.ms_5,
  ms_xxl_auto: dflt.ms_auto,
  me_xxl_0: dflt.me_0,
  me_xxl_1: dflt.me_1,
  me_xxl_2: dflt.me_2,
  me_xxl_3: dflt.me_3,
  me_xxl_4: dflt.me_4,
  me_xxl_5: dflt.me_5,
  me_xxl_auto: dflt.me_auto,
  mx_xxl_0: dflt.mx_0,
  mx_xxl_1: dflt.mx_1,
  mx_xxl_2: dflt.mx_2,
  mx_xxl_3: dflt.mx_3,
  mx_xxl_4: dflt.mx_4,
  mx_xxl_5: dflt.mx_5,
  mx_xxl_auto: dflt.mx_auto,
  my_xxl_0: dflt.my_0,
  my_xxl_1: dflt.my_1,
  my_xxl_2: dflt.my_2,
  my_xxl_3: dflt.my_3,
  my_xxl_4: dflt.my_4,
  my_xxl_5: dflt.my_5,
  my_xxl_auto: dflt.my_auto,
  m_xxl_0: dflt.m_0,
  m_xxl_1: dflt.m_1,
  m_xxl_2: dflt.m_2,
  m_xxl_3: dflt.m_3,
  m_xxl_4: dflt.m_4,
  m_xxl_5: dflt.m_5,
  m_xxl_auto: dflt.m_auto,

  pt_xxl_0: dflt.pt_0,
  pt_xxl_1: dflt.pt_1,
  pt_xxl_2: dflt.pt_2,
  pt_xxl_3: dflt.pt_3,
  pt_xxl_4: dflt.pt_4,
  pt_xxl_5: dflt.pt_5,
  pt_xxl_auto: dflt.pt_auto,
  pb_xxl_0: dflt.pb_0,
  pb_xxl_1: dflt.pb_1,
  pb_xxl_2: dflt.pb_2,
  pb_xxl_3: dflt.pb_3,
  pb_xxl_4: dflt.pb_4,
  pb_xxl_5: dflt.pb_5,
  pb_xxl_auto: dflt.pb_auto,
  ps_xxl_0: dflt.ps_0,
  ps_xxl_1: dflt.ps_1,
  ps_xxl_2: dflt.ps_2,
  ps_xxl_3: dflt.ps_3,
  ps_xxl_4: dflt.ps_4,
  ps_xxl_5: dflt.ps_5,
  ps_xxl_auto: dflt.ps_auto,
  pe_xxl_0: dflt.pe_0,
  pe_xxl_1: dflt.pe_1,
  pe_xxl_2: dflt.pe_2,
  pe_xxl_3: dflt.pe_3,
  pe_xxl_4: dflt.pe_4,
  pe_xxl_5: dflt.pe_5,
  pe_xxl_auto: dflt.pe_auto,
  px_xxl_0: dflt.px_0,
  px_xxl_1: dflt.px_1,
  px_xxl_2: dflt.px_2,
  px_xxl_3: dflt.px_3,
  px_xxl_4: dflt.px_4,
  px_xxl_5: dflt.px_5,
  px_xxl_auto: dflt.px_auto,
  py_xxl_0: dflt.py_0,
  py_xxl_1: dflt.py_1,
  py_xxl_2: dflt.py_2,
  py_xxl_3: dflt.py_3,
  py_xxl_4: dflt.py_4,
  py_xxl_5: dflt.py_5,
  py_xxl_auto: dflt.py_auto,
  p_xxl_0: dflt.p_0,
  p_xxl_1: dflt.p_1,
  p_xxl_2: dflt.p_2,
  p_xxl_3: dflt.p_3,
  p_xxl_4: dflt.p_4,
  p_xxl_5: dflt.p_5,
  p_xxl_auto: dflt.p_auto,

  d_xxl_none: { display: "none" },
  d_xxl_block: { display: "flex" },
};
